### ISSUE TITLE
ModuleNotFoundError: No module named 'production_settings'

### ISSUE THREAD

**Issue by ginkel** [Techwolf12/pretix-roomsharing#9]
Hi there,

when attempting to install `pretix-roomsharing` on top of Pretix 2024.3, I am getting the following error:

```
7.460 Building wheels for collected packages: pretix-roomsharing, googlemaps, wallet-py3k
7.460   Building wheel for pretix-roomsharing (pyproject.toml): started
7.603   Building wheel for pretix-roomsharing (pyproject.toml): finished with status 'error'
7.607   error: subprocess-exited-with-error
7.607   
7.607   × Building wheel for pretix-roomsharing (pyproject.toml) did not run successfully.
7.607   │ exit code: 1
7.607   ╰─> [69 lines of output]
7.607       running bdist_wheel
7.607       running build
7.607       Traceback (most recent call last):
7.607         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
7.607           main()
7.607         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
7.607           json_out['return_val'] = hook(**hook_input['kwargs'])
7.607                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
7.607           return _build_backend().build_wheel(wheel_directory, config_settings,
7.607                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 410, in build_wheel
7.607           return self._build_with_temp_dir(
7.607                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
7.607           self.run_setup()
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
7.607           super().run_setup(setup_script=setup_script)
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
7.607           exec(code, locals())
7.607         File "<string>", line 3, in <module>
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
7.607           return distutils.core.setup(**attrs)
7.607                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
7.607           return run_commands(dist)
7.607                  ^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
7.607           dist.run_commands()
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
7.607           self.run_command(cmd)
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 967, in run_command
7.607           super().run_command(command)
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
7.607           cmd_obj.run()
7.607         File "/tmp/pip-build-env-a2t46xck/normal/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
7.607           self.run_command("build")
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
7.607           self.distribution.run_command(command)
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 967, in run_command
7.607           super().run_command(command)
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
7.607           cmd_obj.run()
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/pretix_plugin_build/build.py", line 20, in run
7.607           management.call_command('compilemessages', verbosity=1)
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
7.607           return command.execute(*args, **defaults)
7.607                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
7.607           output = self.handle(*args, **options)
7.607                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/django/core/management/commands/compilemessages.py", line 90, in handle
7.607           basedirs.extend(settings.LOCALE_PATHS)
7.607                           ^^^^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in __getattr__
7.607           self._setup(name)
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in _setup
7.607           self._wrapped = Settings(settings_module)
7.607                           ^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/tmp/pip-build-env-a2t46xck/overlay/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
7.607           mod = importlib.import_module(self.SETTINGS_MODULE)
7.607                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
7.607           return _bootstrap._gcd_import(name[level:], package, level)
7.607                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7.607         File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
7.607         File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
7.607         File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
7.607       ModuleNotFoundError: No module named 'production_settings'
7.607       [end of output]
7.607   
7.607   note: This error originates from a subprocess, and is likely not a problem with pip.
7.608   ERROR: Failed building wheel for pretix-roomsharing
```

To reproduce, run `docker build .` on a clone of https://github.com/Mind-Hochschul-Netzwerk/docker-pretix/tree/pretix-roomsharing

Thanks,
Thilo

**Comment by Procuria** [comment]
I encountered the exact same problem. Do we already have any hints?

**Comment by knorr3** [comment]
Doing `export DJANGO_SETTINGS_MODULE=` did the trick for me. See more at
https://github.com/pc-coholic/pretix-cashpayment/issues/5
